---
nginx:
  - name: nginx
    chart:
      name: bitnami/nginx
      version: 8.9.1
    installed: 'true' # mind the quotation marks. otherwise value is treated as bool during parsing
    version: 1.19.10
    namespace: nginx