name: buildflow
on: [push]

jobs:

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: setup env
        run: |
          go version
          echo "___"
          go mod vendor
          echo "___"
          go mod verify
      - name: go test
        run: go test .

  go-build:
    name: build
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: setup env
        run: |
          go version
          echo "___"
          go mod vendor
          echo "___"
          go mod verify
      - name: build binary
        run: go build -o ./bin/clusterfilectl -ldflags "-X main.GitCommit=${{ github.sha }}" .
      - name: run executable
        run: ./bin/clusterfilectl --help
