name: buildflow
on: [push]

jobs:

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: setup env
        run: |
          go version
          echo "___"
          go mod vendor
          echo "___"
          go mod verify
      - name: unit tests
        run: |
          make unit-tests

  go-build:
    name: build
    needs:
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: setup env
        run: |
          go version
          echo "___"
          go mod vendor
          echo "___"
          go mod verify
      - name: build binary
        run: go build -o ./bin/clusterfilectl -ldflags "-X main.AppVersion=${{ github.sha }}" .
      - name: run executable
        run: ./bin/clusterfilectl --help

  app-tests:
    name: app-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - uses: engineerd/setup-kind@v0.5.0
      - run: ls -all ~/.kube
      - name: setup env
        run: |
          go version
          echo "___"
          go mod vendor
          echo "___"
          go mod verify
      - name: go test
        run:  |
          make app-tests