name: buildflow
on: [push]

jobs:

  unit-tests:
    name: unit-tests
    continue-on-error: true #until all tests are implemented in a proper manner just go on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: make magic
        run: |
          make go-mod
          make unit-tests

  app-tests:
    name: app-tests
    continue-on-error: true #until all tests are implemented in a proper manner just go on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - uses: engineerd/setup-kind@v0.5.0
      - name: make magic
        run: |
          make go-mod
          make app-tests

  go-build:
    name: build
    needs:
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: make magic
        run: |
          make build GIT_COMMIT=${{ github.sha }}
          make run-help
